In [2]:
# Import packages
from dash import Dash, html, dcc, callback, Output, Input
import pandas as pd
import plotly.express as px
from sklearn.linear_model import LinearRegression
from statistics import NormalDist

# Incorporate data
df = pd.read_csv(r"./data/Aug13.csv")

In [3]:
selected_region = "EU"
selected_scenario = "STEPS"

In [4]:
dff = df[df["region"] == selected_region]
dff = dff[dff["scenario"] == selected_scenario]
dff

year  total_energy_supply  renewables  nuclear  natural_gas      oil  \
0  2010              64475.0      7744.0   9322.0      15187.0  21183.0   
1  2015              59663.0      8997.0   8582.0      12384.0  19109.0   
2  2021              58896.0     10818.0   7986.0      14185.0  18311.0   
3  2022              56179.0     11081.0   6624.0      12301.0  18385.0   
4  2030              51700.0     15845.0   6804.0      10389.0  15165.0   
5  2035              48348.0     18506.0   6155.0       8916.0  12286.0   
6  2040              45817.0     20215.0   5853.0       7705.0   9991.0   
7  2045              43977.0     21542.0   5755.0       6471.0   8424.0   
8  2050              43145.0     22337.0   6282.0       5455.0   7425.0   

      coal  total_co2  transportation  building  industrial_production  \
0  10566.0    3310.90         7196.42  23160.19                 413.37   
1  10023.0    2982.56         7336.20  24460.81                 380.46   
2   6961.0    2744.43         8021.48  25938.56                 408.47   
3   7190.0    2662.45         8249.53  26192.51                 384.03   
4   3123.0    1885.37         8676.56  28129.40                 399.19   
5   2212.0    1500.88         8833.06  29063.44                 402.07   
6   1829.0    1230.60         8940.73  29787.14                 403.42   
7   1595.0    1023.42         9084.65  30385.32                 403.88   
8   1467.0     881.65         9247.34  30898.33                 404.68   

   household  gdp_per_capita region scenario  
0     178.20        46192.24     EU    STEPS  
1     183.16        48392.31     EU    STEPS  
2     188.55        52413.24     EU    STEPS  
3     190.09        54046.32     EU    STEPS  
4     194.41        62036.00     EU    STEPS  
5     195.76        66757.21     EU    STEPS  
6     196.03        71054.48     EU    STEPS  
7     195.62        75619.56     EU    STEPS  
8     194.65        80762.00     EU    STEPS

In [5]:
X = dff["year"].values.reshape(-1, 1)
y = dff["total_co2"].values

In [6]:
X

array([[2010],
       [2015],
       [2021],
       [2022],
       [2030],
       [2035],
       [2040],
       [2045],
       [2050]])

In [7]:
# Create a linear regression model and fit it to the data
model = LinearRegression()
model.fit(X, y)

# Make the prediction
y_pred = model.predict(X)
y_pred

array([3327.70057473, 2998.28919348, 2602.99553598, 2537.11325973,
       2010.05504972, 1680.64366847, 1351.23228722, 1021.82090597,
        692.40952471])

In [8]:
def confidence_interval(data, confidence=0.95):
    dist = NormalDist.from_samples(data)
    z = NormalDist().inv_cdf((1 + confidence) / 2.0)
    h = dist.stdev * z / ((len(data) - 1) ** 0.5)
    return h

In [11]:
CI = confidence_interval(y_pred)
CI

629.1946064337326

In [13]:
y_pred

array([3327.70057473, 2998.28919348, 2602.99553598, 2537.11325973,
       2010.05504972, 1680.64366847, 1351.23228722, 1021.82090597,
        692.40952471])

In [12]:
y_pred + CI

array([3956.89518116, 3627.48379991, 3232.19014241, 3166.30786616,
       2639.24965616, 2309.8382749 , 1980.42689365, 1651.0155124 ,
       1321.60413115])

In [14]:
import scipy

scipy.stats.norm.ppf(0.975)

np.float64(1.959963984540054)

In [4]:
import pandas as pd

df = pd.read_csv(r"./data/WEO2023_Extended_Data_Regions_Full_Unsorted.csv")
df = df.drop(df[df.scenario == "Net Zero Emissions by 2050 Scenario"].index)

selected_region = "North America"

dff = df[df.flow == "Total energy supply"]
dff = dff[dff.category == "Energy"]
dff = dff[dff["product"] == "Total"]
dff = dff[dff["region"] == selected_region]
dff_steps = dff[dff["scenario"] == "Stated Policies Scenario"]
dff_aps = dff[dff["scenario"] == "Announced Pledges Scenario"]

In [5]:
dff_steps

publication                  scenario category product  \
0  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
1  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
2  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
3  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
4  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
5  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
6  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
7  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   
8  World Energy Outlook 2023  Stated Policies Scenario   Energy   Total   

                  flow unit         region  year     value  
0  Total energy supply   PJ  North America  2010  112433.0  
1  Total energy supply   PJ  North America  2015  112723.0  
2  Total energy supply   PJ  North America  2021  111555.0  
3  Total energy supply   PJ  North America  2022  114460.0  
4  Total energy supply   PJ  North America  2030  108324.0  
5  Total energy supply   PJ  North America  2035  103875.0  
6  Total energy supply   PJ  North America  2040  101897.0  
7  Total energy supply   PJ  North America  2045  101097.0  
8  Total energy supply   PJ  North America  2050  101224.0

In [6]:
dff_aps

publication                    scenario category product  \
9      World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
10     World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
11     World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
12     World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
13     World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
30024  World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
30025  World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
30026  World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   
30027  World Energy Outlook 2023  Announced Pledges Scenario   Energy   Total   

                      flow unit         region  year     value  
9      Total energy supply   PJ  North America  2030  103419.0  
10     Total energy supply   PJ  North America  2035   96164.0  
11     Total energy supply   PJ  North America  2040   91626.0  
12     Total energy supply   PJ  North America  2045   88508.0  
13     Total energy supply   PJ  North America  2050   87469.0  
30024  Total energy supply   PJ  North America  2010  112433.0  
30025  Total energy supply   PJ  North America  2015  112723.0  
30026  Total energy supply   PJ  North America  2021  111555.0  
30027  Total energy supply   PJ  North America  2022  114460.0

In [1]:
import pandas as pd

df = pd.read_csv(r"./data/WEO2023_Extended_Data_Regions_Full_Sorted.csv")
df = df.drop(df[df.scenario == "Net Zero Emissions by 2050 Scenario"].index)

selected_region = "North America"
selected_scenario = "Stated Policies Scenario"

dff = df[df.flow == "Total energy supply"]
dff = dff[dff.category == "Energy"]
dff = dff[dff["product"] == "Total"]
dff = dff[dff["region"] == selected_region]
dff = dff[dff["scenario"] == selected_scenario]

# Reshape the data for scikit-learn
X = dff["year"].values.reshape(-1, 1)
y = dff["value"].values

In [2]:
X

array([[2010],
       [2015],
       [2021],
       [2022],
       [2030],
       [2035],
       [2040],
       [2045],
       [2050]])

In [3]:
y

array([112433., 112723., 111555., 114460., 108324., 103875., 101897.,
       101097., 101224.])